name: Bug Report
description: Report a bug in RootSpec
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before submitting, please search existing issues to avoid duplicates.

  - type: input
    id: version
    attributes:
      label: RootSpec Version
      description: What version of RootSpec are you using?
      placeholder: "4.0.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: "18.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I run `rootspec init`, I get an error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `rootspec init`
        2. Select option X
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The framework should be initialized successfully...

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I got this error message...

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error messages or logs
      render: shell
      placeholder: |
        Error: ENOENT: no such file or directory
        at ...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This only happens when...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version of RootSpec
          required: false
        - label: I have included all required information above
          required: true
